AwsRegion: "ca-central-1"
CognitoClientID: ""
DbHost: 192.168.86.137
DbName: "gales-sales"
DbPassword: ""
DbUser: ""
S3Bucket: "gsales-reports"
S3FilePrefix: "reports"
SsmPath: "gsales-xls-reports"
Stage: "prod"
